"""revocation list

Revision ID: f8ff972c71f7
Revises: 55ed731910a8
Create Date: 2026-09-05 19:52:24.771019
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'f8ff972c71f7'
down_revision: str | None = '55ed731910a8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_slug', sa.String(length=64), nullable=True),
    sa.Column('min_token_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revocations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revocations'))
    )
    op.create_index(op.f('ix_revocations_created_at'), 'revocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_revocations_expires_at'), 'revocations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revocations_platform_slug'), 'revocations', ['platform_slug'], unique=False)
    op.create_index(op.f('ix_revocations_user_id'), 'revocations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revocations_user_id'), table_name='revocations')
    op.drop_index(op.f('ix_revocations_platform_slug'), table_name='revocations')
    op.drop_index(op.f('ix_revocations_expires_at'), table_name='revocations')
    op.drop_index(op.f('ix_revocations_created_at'), table_name='revocations')
    op.drop_table('revocations')
    # ### end Alembic commands ###
